#!/usr/bin/env python3
"""Assemble the web page the FEN page's QR code opens -> build/site/.

The page (site/) draws the position with the game's own bitmaps: this
copies site/ and writes sprites.js, holding src/sprites.bin (base64) and the
numeric #defines of src/sprites.h, so the page and SCHAKEN.GFX always share
one set of pieces. The GitHub Pages workflow publishes build/site/; to look
at it locally, `make site` and serve that directory (ES modules do not load
from file:// URLs):

    python3 -m http.server -d build/site
"""
import base64
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "build/site"


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    shutil.copytree(ROOT / "site", OUT)
    defines = {name: int(value) for name, value in
               re.findall(r"^#define (\w+)\s+(\d+)\b", (ROOT / "src/sprites.h").read_text(), re.M)}
    data = base64.b64encode((ROOT / "src/sprites.bin").read_bytes()).decode()
    (OUT / "sprites.js").write_text(
        "// Generated by tools/gen_site.py from src/sprites.bin and src/sprites.h -- do not edit.\n"
        f"export const GFX_OFFSETS = {json.dumps(defines, indent=1)};\n"
        f"export const GFX_BASE64 = \"{data}\";\n")
    print(f"wrote {OUT.relative_to(ROOT)}/ ({len(defines)} offsets, {len(data)} base64 characters)")


if __name__ == "__main__":
    main()
