/* Generated by tools/gen_splash.py -- do not edit. The title picture's
 * run-length data, the second part of SCHAKEN.GFX (src/splash.rle). */
#ifndef SPLASH_H
#define SPLASH_H

#define SPLASH_RLE_SIZE 7136
#define SPLASH_RECORDS  56

#endif
