/* Generated by tools/gen_sprites.py -- do not edit. Offsets of the bitmaps
 * in gfx[], which holds src/sprites.bin (the first part of SCHAKEN.GFX).
 * Bitmaps are one square (6 bytes) wide, row-major, MSB = leftmost dot. */
#ifndef SPRITES_H
#define SPRITES_H

#define GFX_SIZE    4308
#define GFX_RECORDS 34                  /* 128-byte records in the file */

#define PIECE_TOP   2                   /* first piece row inside a square */
#define PIECE_ROWS  25
#define PIECE_BYTES 150
#define MARK_CURSOR_TOP  0
#define MARK_CURSOR_ROWS 29
#define MARK_SELECT_TOP  0
#define MARK_SELECT_ROWS 29
#define MARK_DOT_TOP  11
#define MARK_DOT_ROWS 8
#define MARK_CAPTURE_TOP  0
#define MARK_CAPTURE_ROWS 29

#define GFX_TILE_LIGHT             0   /* light-square dither, 30 rows: start a row in on odd lines */
#define GFX_PIECE_WHITE          180   /* White P N B R Q K */
#define GFX_PIECE_BLACK         1080   /* Black P N B R Q K */
#define GFX_PIECE_MASK          1980   /* halo masks P N B R Q K */
#define GFX_MARK_CURSOR         2880   /* cursor marker */
#define GFX_MARK_CURSOR_MASK    3054   /* cursor halo */
#define GFX_MARK_SELECT         3228   /* select marker */
#define GFX_MARK_SELECT_MASK    3402   /* select halo */
#define GFX_MARK_DOT            3576   /* dot marker */
#define GFX_MARK_DOT_MASK       3624   /* dot halo */
#define GFX_MARK_CAPTURE        3672   /* capture marker */
#define GFX_MARK_CAPTURE_MASK   3846   /* capture halo */
#define GFX_FILE_GLYPHS         4020   /* a-h, 2 bytes x 12 rows, moved right by 4 dots (centred under a square) */
#define GFX_RANK_GLYPHS         4212   /* 1-8, 1 byte x 12 rows, moved left by a dot (clear of the frame) */

extern unsigned char gfx[];
#define GFX(offset) (gfx + (offset))
/* colour 0 White, 1 Black; type PAWN..KING */
#define PIECE_IMAGE(black, type) GFX((black) ? GFX_PIECE_BLACK + ((type) - 1) * PIECE_BYTES \
                                             : GFX_PIECE_WHITE + ((type) - 1) * PIECE_BYTES)
#define PIECE_MASK(type) GFX(GFX_PIECE_MASK + ((type) - 1) * PIECE_BYTES)
#define FILE_GLYPH(i) GFX(GFX_FILE_GLYPHS + (i) * 24)
#define RANK_GLYPH(i) GFX(GFX_RANK_GLYPHS + (i) * 12)

#endif
